Build TAS2505 sound codec

diff --git a/stage2-rak/02-kernel/files/make b/stage2-rak/02-kernel/files/make
--- a/stage2-rak/02-kernel/files/make
+++ b/stage2-rak/02-kernel/files/make
@@ -5,17 +5,17 @@ usage() {
     echo "Raspberry Pi Kernel Builder Utility"
     echo ""
     echo "Commands:"
-    echo " * init           : initializes or resets the linux kernel repository (run this the first time)"
-    echo " * add <path>     : add extra driver"
-    echo " * default        : resets the configuration to defaults"
-    echo " * config         : allows you to define a specific configuration"
-    echo " * build          : builds the kernel based on the configuration in .config "
-    echo " * zip            : ZIPs all the required files, root folder is rootfs"
-    echo " * copy <folder>  : copies the kernel and modules to the given folder"
+    echo " * init             : initializes or resets the linux kernel repository (run this the first time)"
+    echo " * add <cmp> <path> : add extra component to given path"
+    echo " * default          : resets the configuration to defaults"
+    echo " * config           : allows you to define a specific configuration"
+    echo " * build            : builds the kernel based on the configuration in .config "
+    echo " * zip              : ZIPs all the required files, root folder is rootfs"
+    echo " * copy <folder>    : copies the kernel and modules to the given folder"
     echo ""
     echo "Environment variables:"
-    echo " * ARCH           : architecture to build the kernel for: 'arm' or 'arm64' (current: ${ARCH})"
-    echo " * CORES          : number of cores used to build the kernel (current: ${CORES})"
+    echo " * ARCH             : architecture to build the kernel for: 'arm' or 'arm64' (current: ${ARCH})"
+    echo " * CORES            : number of cores used to build the kernel (current: ${CORES})"
     echo ""
     echo "Syntax: $0 [command]"
     echo ""
@@ -59,6 +59,9 @@ if [[ $? -ne 0 ]]; then
     exit 1
 fi
 
+# Compiler command
+MAKE="make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=${COMPILER}"
+
 # Get option
 if [ $#  -lt 1 ]; then
     usage
@@ -89,40 +92,45 @@ case ${OPTION} in
 
     "default" )
         pushd linux >> /dev/null
-        make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=${COMPILER} bcm2711_defconfig
+        ${MAKE} bcm2711_defconfig
         popd >> /dev/null
 
         ;;
 
     "config" )
         pushd linux >> /dev/null
-        make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=${COMPILER} menuconfig
+        ${MAKE} menuconfig
         popd >> /dev/null
 
         ;;
 
     "add") 
-        if [ $#  -lt 2 ]; then
+        if [ $#  -lt 3 ]; then
             usage
             exit 0
         fi
-        DIR=$2
-        if [ ! -d $DIR ]; then
-            echo "ERROR: \"$DIR\" not found"
+        COMPONENT=$2
+        PATH=$3
+        if [ ! -d ${COMPONENT} ]; then
+            echo "ERROR: \"${COMPONENT}\" not found"
             exit 1
         fi
-        cp -r $DIR linux/drivers/
-        NAME=${DIR#*/}
-        echo "obj-y += $NAME/" >> linux/drivers/Makefile
-        sed "s/endmenu/source \"drivers\/$NAME\/Kconfig\"\nendmenu/" -i linux/drivers/Kconfig
+        if [ ! -d linux/${PATH} ]; then
+            echo "ERROR: \"${PATH}\" not found"
+            exit 1
+        fi
+        /bin/cp -r ${COMPONENT} linux/${PATH}/
+        NAME=${COMPONENT##*/}
+        echo "obj-y += ${NAME}/" >> linux/${PATH}/Makefile
+        echo "source \"${PATH}/${NAME}/Kconfig\"" >> linux/${PATH}/Kconfig
         ;;
     
     "build" )
         rm -rf modules
         mkdir modules
         pushd linux >> /dev/null
-        make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=${COMPILER} ${IMAGE} modules dtbs
-        env PATH=$PATH make ARCH=${ARCH} CROSS_COMPILE=${COMPILER} INSTALL_MOD_PATH=../modules modules_install
+        ${MAKE} ${IMAGE} modules dtbs
+        env PATH=$PATH ${MAKE} INSTALL_MOD_PATH=../modules modules_install
         popd >> /dev/null
 
         ;;
@@ -176,7 +184,7 @@ case ${OPTION} in
         ;;
 
     *)
-        echo "Wrong command (${OPTION}), supported values are 'init', 'add', 'default', 'config', 'build', 'zip' or 'copy'"
+        echo "Wrong command (${OPTION}), supported values are 'init', 'add', 'default', 'config', 'build' or 'copy'"
         
         ;;
 
